spring.application.name=PatientManagement
spring.datasource.url=jdbc:postgresql://localhost:5432/patientdb
spring.datasource.username=postgres
spring.datasource.password=prati

server.servlet.context-path=/api/v1
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.security.user.name=user
spring.security.user.password=pass
jwt.secretKey= 8f7d1c5a92b4e6f83d7a1b9c4e5f6a7b9d8c1e2f3a4b5c6d7e8f9a1b2c3d4e5

logging.level.org.springframework.security=DEBUG